.TH MGREP 1
.SH NAME
mgrep \- print lines that match billions of strings efficiently
.SH SYNOPSIS
.B mgrep
[\fB\fR \fICOMMAND\fR]
[\fB\-\-help]
[\fB\-\-version]
.SH DESCRIPTION
.B mgrep
is a tool developed by Manhong Dai and Fan Meng in MNI, U of Michigan. A typical use case is to match billions of varations of ontological terms in free text, such as https://www.bioontology.org/wiki/Annotator_Web_service.

--help for detail, --version for version, copyright and citation.

mgrep has three commands, 'match', 'index' and 'extend'. use \-h with each command to show help
